kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.inventory-events-in.connector=smallrye-kafka
mp.messaging.incoming.inventory-events-in.topic=inventory-events
mp.messaging.incoming.inventory-events-in.group.id=payment-service
mp.messaging.incoming.inventory-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer