kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.inventory-events-in.connector=smallrye-kafka
mp.messaging.incoming.inventory-events-in.topic=inventory-events
mp.messaging.incoming.inventory-events-in.group.id=payment-service
mp.messaging.incoming.inventory-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer



mp.messaging.outgoing.payment-events-out.connector=smallrye-kafka
mp.messaging.outgoing.payment-events-out.topic=payment-events

mp.messaging.outgoing.payment-events-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.payment-events-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer